### ISSUE TITLE
Add Hacktoberfest topic

### ISSUE THREAD

**Issue by hahahandroid** [amykapernick/quokkas#20]
Hi! Thanks for maintaining this wonderful repo! 

Would you mind to add a `hacktoberfest` topic according to the new Hacktoberfest participation guidelines? This will enable the contributions to be counted as a Hacktoberfest participation.

More info:
https://hacktoberfest.digitalocean.com/hacktoberfest-update
https://www.youtube.com/watch?v=FxBv4FMcDgo

**Comment by amykapernick** [comment]
Has been added
